/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

import static Classes.ProjectAvoe.deserializa;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author guisi
 */
public class LoginInterface extends javax.swing.JFrame {

    private JPanel JPanel;
    private JPanel JPanel1;
    private JPanel BotãoEnrar;
    
    static String fileName = "D:\\Documentos\\Documentos do Usuário\\Acadêmico\\IFPB\\E.C\\Matérias\\Laboratório de POO\\Documentos\\Programas\\ProjectAvoe\\src\\Classes\\saves\\cadastro.ser";
    //static String fileName = "C:\\Users\\guisi\\OneDrive\\Documentos\\Engenharia de Computação\\Programação Orientada a Objetos\\ProjectAvoe\\src\\Classes\\saves\\cadastro.ser";
    /**
     * Creates new form AvoeInterface
     */
    public LoginInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        Background = new javax.swing.JPanel();
        AvoeLogo = new javax.swing.JLabel();
        FloatPanel = new javax.swing.JPanel();
        UserCamp = new javax.swing.JTextField();
        UserIcon = new javax.swing.JLabel();
        Separator = new javax.swing.JSeparator();
        PasswordCamp = new javax.swing.JPasswordField();
        PasswordIcon = new javax.swing.JLabel();
        Separator2 = new javax.swing.JSeparator();
        LoginButton = new javax.swing.JPanel();
        ButtonLabel = new javax.swing.JLabel();
        ClientLoginName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Project Avoe - Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(270, 40));
        setResizable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Background, org.jdesktop.beansbinding.ELProperty.create("${background}"), Background, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        AvoeLogo.setBackground(new java.awt.Color(0, 0, 0));
        AvoeLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AvoeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GraficInterface/icons/iconSup.png"))); // NOI18N

        FloatPanel.setBackground(new java.awt.Color(153, 153, 153));

        UserCamp.setBackground(FloatPanel.getBackground());
        UserCamp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserCamp.setBorder(null);
        UserCamp.setSelectionColor(new java.awt.Color(102, 102, 102));
        UserCamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserCampActionPerformed(evt);
            }
        });

        UserIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GraficInterface/icons/icons8_Customer_26px.png"))); // NOI18N
        UserIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Separator.setBackground(FloatPanel.getBackground());
        Separator.setForeground(FloatPanel.getForeground());

        PasswordCamp.setBackground(FloatPanel.getBackground());
        PasswordCamp.setBorder(null);
        PasswordCamp.setDragEnabled(true);
        PasswordCamp.setSelectionColor(new java.awt.Color(102, 102, 102));

        PasswordIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GraficInterface/icons/icons8_Lock_26px.png"))); // NOI18N

        Separator2.setBackground(FloatPanel.getBackground());
        Separator2.setForeground(FloatPanel.getForeground());

        LoginButton.setBackground(new java.awt.Color(51, 51, 51));
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginButtonMouseExited(evt);
            }
        });

        ButtonLabel.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 18)); // NOI18N
        ButtonLabel.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonLabel.setText("Entrar");

        javax.swing.GroupLayout LoginButtonLayout = new javax.swing.GroupLayout(LoginButton);
        LoginButton.setLayout(LoginButtonLayout);
        LoginButtonLayout.setHorizontalGroup(
            LoginButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginButtonLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(ButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );
        LoginButtonLayout.setVerticalGroup(
            LoginButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        ClientLoginName.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        ClientLoginName.setForeground(new java.awt.Color(255, 255, 255));
        ClientLoginName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ClientLoginName.setText("Client Login");

        javax.swing.GroupLayout FloatPanelLayout = new javax.swing.GroupLayout(FloatPanel);
        FloatPanel.setLayout(FloatPanelLayout);
        FloatPanelLayout.setHorizontalGroup(
            FloatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FloatPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(FloatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UserIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PasswordIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(FloatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Separator2)
                    .addComponent(PasswordCamp)
                    .addComponent(Separator)
                    .addComponent(UserCamp))
                .addContainerGap(122, Short.MAX_VALUE))
            .addComponent(ClientLoginName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FloatPanelLayout.setVerticalGroup(
            FloatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FloatPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(ClientLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(FloatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(UserCamp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addGroup(FloatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FloatPanelLayout.createSequentialGroup()
                        .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PasswordCamp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PasswordIcon))
                .addGap(1, 1, 1)
                .addComponent(Separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AvoeLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(FloatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(AvoeLogo))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(FloatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserCampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserCampActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserCampActionPerformed

    private void LoginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseEntered
        setcolor(LoginButton);
    }//GEN-LAST:event_LoginButtonMouseEntered

    private void LoginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseExited
        resetcolor(LoginButton);
    }//GEN-LAST:event_LoginButtonMouseExited
    
    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        Cadastrados cadastro = deserializa(fileName);
        
        Usuario logado = null;
        
        cadastro.administradorPadrao();
        
        logado = cadastro.autentica(UserCamp.getText(), PasswordCamp.getText());
        if (logado != null) {
            MainInterface main = new MainInterface(cadastro, logado);
            main.setVisible(true);
            this.dispose();
        }
        else {
            JOptionPane.showMessageDialog(null,"Usuário ou senha incorretos.");
            UserCamp.setText(null);
            PasswordCamp.setText(null);
        }
    }//GEN-LAST:event_LoginButtonMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvoeLogo;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel ButtonLabel;
    private javax.swing.JLabel ClientLoginName;
    private javax.swing.JPanel FloatPanel;
    private javax.swing.JPanel LoginButton;
    private javax.swing.JPasswordField PasswordCamp;
    private javax.swing.JLabel PasswordIcon;
    private javax.swing.JSeparator Separator;
    private javax.swing.JSeparator Separator2;
    private javax.swing.JTextField UserCamp;
    private javax.swing.JLabel UserIcon;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void setcolor(JPanel jPanel1) {
        jPanel1.setBackground(new Color(102,102,102));
    }
    
    private void resetcolor(JPanel jPanel1) {
        jPanel1.setBackground(new Color(51,51,51));
    }
}
